server:
  port: 8080
spring:
  datasource:
    name: '主数据库'
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.143.198.241:3306/main
    username: root
    password: 12345abc

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '动态数据源'
      paths-to-match: '/**'
      packages-to-scan: cn.bcf.controller
knife4j:
  enable: true
  setting:
    language: zh_cn